name: Deploy website

on:
  push:
    branches: [ "main", "login-register" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with: 
          node-version: 22
          cache: "npm"
      
      - name: Install Netlify
        run: npm add -g netlify-cli

      - name: Install Dependencies
        run: npm install

      - name: Debug ENV
        run: echo "VITE_BACKEND_URL is $VITE_BACKEND_URL"
        env:
          VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}

      - name: Build project
        run: npm run build
        env:
          VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy --prod \
            --dir dist \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}